# Generated by Django 4.1.7 on 2023-03-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_range', models.TextField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('stat', models.CharField(blank=True, max_length=255, null=True)),
                ('target_class', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('author', models.CharField(blank=True, max_length=45, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
