# Generated by Django 3.2.13 on 2023-03-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='subject',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
