# Generated by Django 3.2.13 on 2023-03-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_youtube_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
