# Generated by Django 3.2.13 on 2023-03-31 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_alter_youtube_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='register',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
