# Generated by Django 3.2.13 on 2023-03-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0007_youtube_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='register',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
