# Generated by Django 3.2.13 on 2023-03-31 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0008_alter_youtube_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='register',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
