# Generated by Django 3.2.13 on 2023-03-31 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0009_alter_youtube_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='register',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
