# Generated by Django 3.2.13 on 2023-04-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0012_alter_youtube_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
